# Generated by Django 4.1.6 on 2023-02-17 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sectionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.section'),
        ),
    ]
