# Generated by Django 4.1.6 on 2023-02-18 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_item_sectionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('modifier_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='id',
            new_name='item_id',
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('items_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.item')),
                ('mod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.modifier')),
            ],
        ),
    ]
