# Generated by Django 4.1.6 on 2023-02-18 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_modifier_rename_id_item_item_id_mapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='modifier',
            old_name='modifier_id',
            new_name='id',
        ),
    ]
