# Generated by Django 4.1.6 on 2023-02-18 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_item_id_item_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='modifier',
            old_name='id',
            new_name='modifier_id',
        ),
    ]
