# Generated by Django 4.1.6 on 2023-02-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_rename_id_item_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifier',
            name='modifier_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
