# Generated by Django 4.1.6 on 2023-02-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_modifier_modifier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='modifier_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
