# Generated by Django 4.1.6 on 2023-02-19 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_item_modifiers_alter_item_sectionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='modifier',
            old_name='modifier_id',
            new_name='id',
        ),
    ]
