# Generated by Django 4.1.6 on 2023-02-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_rename_items_id_mapping_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapping',
            old_name='items',
            new_name='items_id',
        ),
        migrations.RenameField(
            model_name='mapping',
            old_name='modifiers',
            new_name='mod_id',
        ),
        migrations.AddField(
            model_name='item',
            name='modifiers',
            field=models.ManyToManyField(blank=True, related_name='modifiers', to='menu.modifier'),
        ),
    ]
