# Generated by Django 4.1.6 on 2023-02-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_rename_items_mapping_items_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='modifiers',
        ),
        migrations.AddField(
            model_name='modifier',
            name='itemid',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='menu.item'),
        ),
    ]
