# Generated by Django 4.1.6 on 2023-02-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_remove_item_modifiers_modifier_itemid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifier',
            name='itemid',
        ),
        migrations.AddField(
            model_name='modifier',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='modifiers', to='menu.item'),
        ),
    ]
